#!/bin/csh

# create the three MPEG title sequences from all the *.tif files with titles

# use each file 125 times in order to have a sequence that lasts 5 seconds (at 25 images per second)

#set quality = 100
set quality = 85

#################################################################
########## first title
#################################################################

 convert -quality $quality \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_01.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_general_02.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
titre_propagation_Europe.tiff \
title_01.mpeg


#################################################################
########## second title
#################################################################

 convert -quality $quality \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
titre_semi_transparence.tiff \
title_02.mpeg

#################################################################
########## third title
#################################################################

 convert -quality $quality \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
titre_propagation_Pacifique.tiff \
title_03.mpeg

