#!/bin/bash -eu

example=$1
dir=$PWD/$example
echo ""; echo "";
echo "you are going to run the example:"
echo "*****$example******"
echo ""; echo "";

cd ../../

mkdir -p SEM zzz_job_info NOISE_TOMOGRAPHY

#cp $dir/A0.II.LHZ.adj                    ./SEM/
#cp $dir/cp_adj_sources                   ./SEM/

cp $dir/adj_traveltime_filter.f90        ./
cp $dir/NOISE123.submit_atten            ./
cp $dir/NOISE_clean_create               ./
cp $dir/NOISE_collect                    ./
cp $dir/NOISE_transfer                   ./

cp $dir/S_squared                        ./NOISE_TOMOGRAPHY
cp $dir/irec_master_noise                ./NOISE_TOMOGRAPHY/
cp $dir/nu_master                        ./NOISE_TOMOGRAPHY/

cp $dir/Par_file_NOISE_*                 ./DATA/
cp $dir/CMTSOLUTION_NOISE                ./DATA/
cp $dir/STATIONS_NOISE                   ./DATA/

#cd SEM
#./cp_adj_sources
#cd ..

ifort -o NOISE_adj adj_traveltime_filter.f90

cp DATA/Par_file_NOISE_1_attenuation DATA/Par_file
rm OUTPUT_FILES/*
make xmeshfem3D
make xspecfem3D
mv bin/xmeshfem3D xmeshfem3D_attenuation
mv bin/xspecfem3D xspecfem3D_attenuation

cp DATA/Par_file_NOISE_1_noattenuation DATA/Par_file
rm OUTPUT_FILES/*
make xmeshfem3D
make xspecfem3D
mv bin/xmeshfem3D xmeshfem3D_noattenuation
mv bin/xspecfem3D xspecfem3D_noattenuation

qsub NOISE123.submit_atten

