#!/bin/bash -eu

example=$1
dir=$PWD/$example
echo ""; echo "";
echo "you are going to run the example:"
echo "*****$example******"
echo ""; echo "";

cd ../../

rm -rf   SEM NOISE_TOMOGRAPHY zzz_$example
mkdir -p SEM NOISE_TOMOGRAPHY zzz_$example/job_info

cp $dir/adj_traveltime_filter.f90        ./
ifort adj_traveltime_filter.f90 -o NOISE_adj

cp $dir/NOISE123.submit_atten            ./
cp $dir/NOISE_clean_create               ./
cp $dir/NOISE_collect                    ./

cp $dir/S_squared                        ./NOISE_TOMOGRAPHY/
cp $dir/irec_master_noise                ./NOISE_TOMOGRAPHY/
cp $dir/nu_master                        ./NOISE_TOMOGRAPHY/

cp $dir/Par_file_NOISE_*                 ./DATA/
cp $dir/CMTSOLUTION_NOISE                ./DATA/CMTSOLUTION
cp $dir/STATIONS_NOISE                   ./DATA/STATIONS
cp $dir/STATIONS_NOISE_ADJOINT           ./DATA/STATIONS_ADJOINT

cp DATA/Par_file_NOISE_1_attenuation DATA/Par_file
rm -rf OUTPUT_FILES/*
make xmeshfem3D
make xspecfem3D
make xcreate_movie_AVS_DX
mv bin/xmeshfem3D xmeshfem3D_attenuation
mv bin/xspecfem3D xspecfem3D_attenuation
mv bin/xcreate_movie_AVS_DX xcreate_movie_AVS_DX_attenuation

cp DATA/Par_file_NOISE_1_noattenuation DATA/Par_file
rm -rf OUTPUT_FILES/*
make xmeshfem3D
make xspecfem3D
make xcreate_movie_AVS_DX
make xcombine_vol_data
mv bin/xmeshfem3D xmeshfem3D_noattenuation
mv bin/xspecfem3D xspecfem3D_noattenuation
mv bin/xcreate_movie_AVS_DX xcreate_movie_AVS_DX_noattenuation
mv bin/xcombine_vol_data    xcombine_vol_data

qsub NOISE123.submit_atten
