#!/bin/bash

machine_new=$1
machine_old=$2
LOCAL_PATH_OLD=$3
LOCAL_PATH_NEW=$4
let myrank=$5
myrank_new=`printf "%06d" $myrank`

##echo "scp $machine_old:$LOCAL_PATH_OLD/proc$myrank_new* $LOCAL_PATH_NEW/"

## 1st way to avoid "argument list too long"
#rm -rf $LOCAL_PATH_NEW
#scp -r $machine_old:$LOCAL_PATH_OLD $LOCAL_PATH_NEW

## 2nd way
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_reg* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_save* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie00* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie01* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie02* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie03* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie04* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie05* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie06* $LOCAL_PATH_NEW/
scp $machine_old:$LOCAL_PATH_OLD/proc"$myrank_new"_surface_movie07* $LOCAL_PATH_NEW/
