#!/bin/bash

machine_new=$1
machine_old=$2
LOCAL_PATH_NEW=$3
LOCAL_PATH_OLD=$4
let myrank=$5
myrank_new=`printf "%06d" $myrank`

##echo "cp $LOCAL_PATH_NEW/proc$myrank_new*kernel* OUTPUT_FILES/"
mv $LOCAL_PATH_NEW/proc$myrank_new*reg1*kernel*.bin OUTPUT_FILES/
mv $LOCAL_PATH_NEW/proc$myrank_new*reg1_*array_dims.txt OUTPUT_FILES/
mv $LOCAL_PATH_NEW/proc$myrank_new*reg1_solver_data*.bin OUTPUT_FILES/
