#
# template to run test
#

parameters:
- name: workingDirectory
  type: string
  default: ''

steps:
- script: |
    WORKDIR=`pwd`
    # test example
    testdir=${{ parameters.workingDirectory }}
    echo "work directory: $WORKDIR"
    echo "test directory: $testdir"
    cd $dir
    ./run_this_example.sh
    # checks script return code
    if [[ $? -ne 0 ]]; then
      # cleanup
      rm -rf OUTPUT_FILES* DATABASES_MPI*
      exit 1
    fi
    # checks output
    echo "testing seismograms:"
    ln -s $WORKDIR/utils/compare_seismogram_correlations.py
    ./compare_seismogram_correlations.py REF_SEIS/ OUTPUT_FILES/
    if [[ $? -ne 0 ]]; then exit 1; fi
    ./compare_seismogram_correlations.py REF_SEIS/ OUTPUT_FILES/ | grep min/max | cut -d \| -f 3 | awk '{print "correlation:",$1; if ($1 < 0.999 ){print $1,"failed"; exit 1;}else{ print $1,"good"; exit 0;}}'
    if [[ $? -ne 0 ]]; then exit 1; fi
    rm -rf OUTPUT_FILES/
  displayName: 'Run Test ${{ parameters.workingDirectory }}'


