#
# template to run test
#

parameters:
- name: workingDirectory
  type: string
  default: ''

steps:
- script: |
    WORKDIR=`pwd`
    # test example
    testdir=${{ parameters.workingDirectory }}
    echo "work directory: $WORKDIR"
    echo "test directory: $testdir"
    echo ""
    cd $dir
    echo "current dir: `pwd`"
    echo ""
    ls -al
    echo ""
    # fails to run..
    #./run_this_example.sh
    ## checks script return code
    #if [[ $? -ne 0 ]]; then
    #  # cleanup
    #  rm -rf OUTPUT_FILES* DATABASES_MPI*
    #  exit 1
    #fi

- bash: . './run_this_example.sh'
  displayName: 'run this example'
  workingDirectory: ${{ parameters.workingDirectory }}

- script: |
    # checks output
    echo "testing seismograms:"
    echo "workdir: $WORKDIR"
    echo "current dir: `pwd`"
    echo
    ln -s $WORKDIR/utils/compare_seismogram_correlations.py
    ./compare_seismogram_correlations.py REF_SEIS/ OUTPUT_FILES/
    if [[ $? -ne 0 ]]; then exit 1; fi
    ./compare_seismogram_correlations.py REF_SEIS/ OUTPUT_FILES/ | grep min/max | cut -d \| -f 3 | awk '{print "correlation:",$1; if ($1 < 0.999 ){print $1,"failed"; exit 1;}else{ print $1,"good"; exit 0;}}'
    if [[ $? -ne 0 ]]; then exit 1; fi
    rm -rf OUTPUT_FILES/
  displayName: 'Run Test ${{ parameters.workingDirectory }}'


